name: svs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
   # basic programs
   - python=3.10
   - pip
   - gitpython
   # scientific python base packages
   - numpy
   - pandas
   - scipy
   # jupyter notebooks
   - ipykernel
   - notebook
   - jupyterlab
   - nb_conda_kernels
   - ipympl
   # python visualization
   - matplotlib
   # machine learning
   - pytorch=2.1
   - pytorch-cuda=11.8
   - torchvision
   - einops
   - scikit-learn
   - scikit-image
   - lightning
   - torchmetrics
   - pip:
      - opencv-python
      - tensorboard
      - nibabel
      - tikzplotlib
      - termcolor
      - tqdm
      - openpyxl
      - torchsummary
      - seaborn
      - elasticdeform
      - monai
      - intensity-normalization
      - natsort
      - batchgenerators
      - tabulate
      - ml_collections
      - hydra-core
      - hydra-joblib-launcher
      # this package
      - -e .
