hydra:
  run:
    dir: results/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: results/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

gpu: [0]
patience: 50

data:
  _target_: 'svs.modules.datasets.LitNNDataset'
  num_workers: 16
  batch_size: 2
  train_config:
    base_dir: 'data/refactor_prep/acdc_lv'
    imgs_dir: 'NIFTI_4D_Datasets'
    segs_dir: 'NIFTI_Single_Ventricle_Segmentations'
    metadata_file: 'Segmentation_volumes.xlsx'
    split: 'train'
    forward_flow_subdir: 'optical_flow/forward'
    backward_flow_subdir: 'optical_flow/backward'
  val_config:
    base_dir: ${data.train_config.base_dir}
    imgs_dir: ${data.train_config.imgs_dir}
    segs_dir: ${data.train_config.segs_dir}
    metadata_file: ${data.train_config.metadata_file}
    split: 'val'
    forward_flow_subdir: ${data.train_config.forward_flow_subdir}
    backward_flow_subdir: ${data.train_config.backward_flow_subdir}
  transforms_config: ${transforms}

defaults:
  - _self_
  - model: unet
  - transforms: custom
  - override hydra/job_logging: custom
