gpu: [0]

data:
  _target_: 'svs.modules.datasets.LitNNDataset'
  num_workers: 8
  batch_size: 4
  train_config:
    base_dir: ''
    imgs_dir: 'NIFTI_4D_Datasets'
    segs_dir: 'NIFTI_Single_Ventricle_Segmentations'
    metadata_file: 'Segmentation_volumes.xlsx'
    split: 'train'
    forward_flow_subdir: 'forward'
    backward_flow_subdir: 'backward'
    transforms: ${transforms.train} 
  val_config:
    base_dir: ${data.train_config.base_dir}
    imgs_dir: ${data.train_config.imgs_dir}
    segs_dir: ${data.train_config.segs_dir}
    metadata_file: ${data.train_config.metadata_file}
    split: 'val'
    forward_flow_subdir: ${data.train_config.forward_flow_subdir}
    backward_flow_subdir: ${data.train_config.backward_flow_subdir}
    transforms: ${transforms.val}

defaults:
  - _self_
  - model: unet
  - transforms: transforms
  - override hydra/job_logging: custom
