_target_: svs.modules.flow.warping.TransformsWarper
# _target_: svs.modules.flow.warping.OpticalFlowWarper

data:
  # Input data will be loaded from this dir
  base_dir: 'data/refactor_prep/acdc_lv'
  imgs_dir: 'NIFTI_4D_Datasets'
  segs_dir: 'NIFTI_Single_Ventricle_Segmentations'
  metadata_file: 'Segmentation_volumes.xlsx'
  
  # Optical flow subdirs
  flow_subdir:
    forward: 'optical_flow/forward'
    backward: 'optical_flow/backward'

  # Output data will be save in this dir
  out_dir: 'results'

warping:
  interpolation:
    type: 'CUBIC_HERMITESPLINE' # Options: {NEAREST, LINEAR, CUBIC_HERMITESPLINE}
    boundary: "MIRROR"          # Options: {NEAREST, MIRROR, REFLECT}

  mesh:
    type: "numDofs"             # Options: {numDofs, fixed}
    length:
      - 1   # lx
      - 1   # ly
      - 1   # lz

debug:
  viz: true
  forward_color: [0, 0, 1]  # blue
  backward_color: [1, 0, 0] # red
  aspect_ratio: 5.0
  gif: true
  dur: 200
