[DATA]
PRETRAINED_DIR = results/CNN_20221026-024558
WEIGHTS_FILENAME = best_val_checkpoint.pth

BASE_PATH_3D = data/singleVentricleData_split
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx
PATIENT_NAME = Adult_11

; test, train, val, full
DATASET = test

OUTPUT_PATH = results/TEST_FT


[PARAMETERS]
NUM_EPOCHS = 500
NUM_GPUS = 1
NUM_WORKERS = 4

# Optim Adam
LR = 1e-3
WEIGHT_DECAY = 1e-4
BETA1 = 0.9
BETA2 = 0.999

# Schedule
STEP_SIZE = 50
GAMMA = 0.8

LOSS_FN = mse
; LOSS_FN = huber
; HUBER_DELTA = 1.35
LOSS_REDUCTION = sum
LOSS_LAMBDA = 5
LOSS_PENALIZATION = 1
LOSS_PENALIZATION_MU = 2e-3


[WARPING]
#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
InterpolationType = LINEAR
; InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


[DATA_AUGMENTATION]