[DATA]
; BASE_PATH_3D = data/singleVentricleData
; BASE_PATH_3D = data/singleVentricleData_flip
; BASE_PATH_3D = data/singleVentricleData_cut
; BASE_PATH_3D = data/singleVentricleData_prolongCubicSmall
BASE_PATH_3D = data/singleVentricleData_prolongCubic_split

VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

OUTPUT_PATH = results

[DEVICE]
cuda_availabe = 1
cuda_device = 1

# 1
[FLIPPING]
flip_all = {Adolescent_7,
            Adolescent_26,
            Adolescent_54,
            Adolescent_75,
            Adult_6,
            Adult_11,
            Adult_16,
            Adult_17,
            Child_27}


# 2
[CUTTING]
xTol = 10
yTol = 10
zTol = 10


# 3
[PROLONGATION]
NX_prolong = 80
NY_prolong = 80
NZ_prolong = 80

# Threshold for prolongated mask binarization
USE_TH = 0
BIN_TH = 0.5

# Pad time
PAD_TIME = 40

[PARAMETERS]
; LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
; InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


# 4
[SPLIT]
validation_patients = {Adolescent_1,
                        Adolescent_20,
                        Adolescent_53,
                        Adolescent_62,
                        Adolescent_107,
                        Adult_3,
                        Adult_11,
                        Adult_24,
                        Adult_36,
                        Adult_62,
                        Adult_104,
                        Child_2,
                        Child_14,
                        Child_24,
                        Child_36,
                        Child_45,
                        Child_53,
                        Child_73}


# 5
[DATA_AUGMENTATION]
# Create new N patientes for each patient in the original dataset
CREATE_NEW = 5

# Flip probabilities
FLIP_X_PROB = 0.0
FLIP_Y_PROB = 0.0
FLIP_Z_PROB = 0.0

# Rotation probability and ranges
ROT_PROB = 0.0
ROT_X_RANGE = 0,360
ROT_Y_RANGE = 0,360
ROT_Z_RANGE = 0,360

# Elastic deformation probability and params
ELASTIC_DEFORM_PROB = 1.0
ELASTIC_DEFORM_GRID = 10
ELASTIC_DEFORM_SIGMA = 2