[DATA]
BASE_PATH_3D = data/singleVentricleData_split_v2
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

OUTPUT_PATH = results
                

[DEVICE]
CUDA_AVAILABLE = 1


[PARAMETERS]
PRETRAINED = 1
CHECKPOINT_FILE = results/CNN_20220809-103422/weights.pth

; unet3d, basic_unet3d, res_unet3d
NET = res_unet3d
USE_MEDIAN_FILTERED_FLOW = 1
NUM_CLASSES = 1
INPUT_CHANNELS = 2
KERNEL_SIZE = 3,3,3
PADDING = 1
TRILINEAR = 0
SHUFFLE = 1
NUM_EPOCHS = 200

RESIDUAL = 1

; Spectral normalization. Reducing the Lipschitz constant of the model
LIPSCHITZ_REGULARIZATION = 0
MAX_LIPSCHITZ_CONSTANT = 0.9
POWER_ITS = 1
POWER_EPS = 1e-8

;relu, prelu
ACTIVATION = leaky_relu
ACTIVATION_SLOPE = 0.1

; mse, huber
LOSS_FN = mse
; LOSS_FN = huber
; HUBER_DELTA = 1.35
LOSS_REDUCTION = sum
LOSS_LAMBDA = 1

LOSS_PENALIZATION = 0
LOSS_PENALIZATION_MU = 10

; Options: 1,4,8
BATCH_SIZE = 1

; Total of GPUs used for training 
NUM_GPUS = 1

; CPU for data loading
NUM_WORKERS = 16

; 3,4,5
NUM_LAYERS = 4

; 8,16,32
FEATURES_START = 16

NUM_RES_UNITS = 1

; Optim Adam
LR = 1e-3
WEIGHT_DECAY = 1e-5
BETA1 = 0.9
BETA2 = 0.999

; LR Schedule
STEP_SIZE = 50
GAMMA = 0.8

[DATA_AUGMENTATION]
HORIZONTAL_FLIP_PROB = 1.0
VERTICAL_FLIP_PROB = 0.0
DEPTH_FLIP_PROB = 0.0


[WARPING]
; LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
InterpolationType = LINEAR
; InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


[DEBUG]
VERBOSE = 1