[DATA]
; BASE_PATH_3D = data/singleVentricleData
; BASE_PATH_3D = data/singleVentricleData_flip
; BASE_PATH_3D = data/singleVentricleData_cut
BASE_PATH_3D = data/singleVentricleData_prolongLinear

VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

OUTPUT_PATH = results

[DEVICE]
cuda_availabe = 1
cuda_device = 1

[FLIPPING]
flip_all = {'Adolescent_7',
            'Adolescent_26',
            'Adolescent_54',
            'Adolescent_75',
            'Adult_6',
            'Adult_11',
            'Adult_16',
            'Adult_17',
            'Child_27'}

[CUTTING]
xTol = 10
yTol = 10
zTol = 10


[PROLONGATION]
NX_prolong = 80
NY_prolong = 80
NZ_prolong = 80
; NZ_prolong = 16


[SPLIT]
validation_patients = {'Adolescent_1',
                        'Adolescent_20',
                        'Adolescent_53',
                        'Adolescent_62',
                        'Adult_3',
                        'Adult_11',
                        'Adult_24',
                        'Adult_36',
                        'Child_2',
                        'Child_14',
                        'Child_24',
                        'Child_36'}

[PARAMETERS]
; LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
; InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT




