[DATA]
; BASE_PATH = "singleVentricleData"
; VOLUMES_SUBDIR_PATH = os.path.sep.join([BASE_PATH, "NIFTI_4D_Datasets"])
; SEGMENTATIONS_SUBDIR_PATH = os.path.sep.join([BASE_PATH, "NIFTI_Single_Ventricle_Segmentations"])
; SEGMENTATIONS_FILE = os.path.sep.join([BASE_PATH, "Segmentation_volumes.xlsx"])
; PATIENT_NAME = "Adult_30"
# PATIENT_NAME = "Adolescent_87"
#PATIENT_NAME = "Child_10"
OUTPUT_PATH = results

##2D##
BASE_PATH_2D = MiddleburyOpticalFlow
Image0_SUB_PATH = other-data-gray/Beanbags/frame07.png
Image1_SUB_PATH = other-data-gray/Beanbags/frame08.png

[DEVICE]
cuda_availabe = 1


[PARAMETERS]
NUM_SCALES = 3
MAX_WARPS = 25
MAX_OUTER_ITERATIONS = 1000

#primalFctWeight_Matching = 1.
#dualFctWeight_TV = 25.
primalFctWeight_Matching = 1.
dualFctWeight_TV = 0.05

PRIMALDUAL_ALGO_TYPE = 2
sigma = 0.5
tau = 0.5
theta = 0.25
gamma = 1.

#InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

[DEBUG]
useDebugOutput = 1




