[DATA]
; BASE_PATH_3D = data/singleVentricleData
BASE_PATH_3D = data/singleVentricleData_prolongLinear_split_x5_N

VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

COMPUTE_ALL_PATIENTS = 1
#if not, choose single patient:
;PATIENT_NAME = Child_2
PATIENT_NAME = Adolescent_68
; PATIENT_NAME = Adolescent_65
; PATIENT_NAME = SyntheticPatient_1
### problems wiht backward flow:
#Adolescent_68
#Adult_7
#Child_26
#Child_19
#Adullt_11
#Adolescent_65

OUTPUT_PATH = results/singleVentricleData_prolongLinear_split_x5_N_OF


[DEVICE]
cuda_availabe = 1


[PARAMETERS]
# Compute the optical flow every n timesteps (-1 means all timesteps)
step = -1

#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

# Forward -> propagation from m0 to mk
# Backward -> propagation from mk to m0
; mode = Forward
mode = Backward

use_indices = 1
dataset = val
from_idx = 0
to_idx = 18

# train -> 0, 24, 48, 72
# val -> 0, 18

# x5
# train -> 0, 108, 216, 324, 432
# val -> 0, 18

# x10
# train -> 0, 198, 396, 594, 792
# val -> 0, 18

# x20
# train -> 0, 378, 756, 1134, 1512
# val -> 0, 18

useAnisotropicDifferentialOp = 1
anisotropicDifferentialOp_alpha = 5.
anisotropicDifferentialOp_beta = 0.5

useGaussianBlur = 1
GaussianBlurSigma = 1.0

# Apply median filter to optical flow estimation
USE_MEDIAN_FILTER = 1
KERNEL_MF = 3

NUM_SCALES = 3
MAX_WARPS = 15
MAX_OUTER_ITERATIONS = 300

# Lambda is weight_Matching
weight_Matching = 1.0
weight_TV = 0.025

PRIMALDUAL_ALGO_TYPE = 2
sigma = 0.5
tau = 0.5
theta = 0.25
gamma = 1.0

; InterpolationType = NEAREST
; InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


[DEBUG]
useDebugOutput = 0




