[DATA]
BASE_PATH_3D = data/singleVentricleData_split
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

OUTPUT_PATH = results


[PARAMETERS]
USE_MEDIAN_FILTERED_FLOW = 1

NUM_WORKERS = 8

SAVE_IMGS = 1
SAVE_IMGS_SLICES = 1
SAVE_NIFTI = 1
SAVE_NZ = 16
SAVE_NY = 200
SAVE_NX = 200

HAUSDORFF_PERCENTILE = 100


[WARPING]
; LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; NEAREST, LINEAR, CUBIC_HERMITESPLINE
InterpolationType = LINEAR

; BoundaryType = NEAREST, REFLECT, MIRROR
BoundaryType = MIRROR
