[DATA]
; BASE_PATH_3D = data/singleVentricleData
BASE_PATH_3D = data/Synthetic3D
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx
PATIENT_NAME = SyntheticPatient_1

# Results from optical flow computation
FWD_OPTFLOW_RESULTS_DIR = results/TVL1OF3DForward_20220408-111639
BWD_OPTFLOW_RESULTS_DIR = results/TVL1OF3DBackward_20220411-100609

[PARAMETERS]
NUM_CLASSES = 1
INPUT_CHANNELS = 1
NUM_LAYERS = 3
FEATURES_START = 4
DROPOUT = 0
DROPOUT_PROB = 0.5
KERNEL_SIZE = 3,3,3
PADDING = 1
TRILINEAR = 0

NUM_EPOCHS = 1
BATCH_SIZE = 1

[DEVICE]
CUDA_AVAILABLE = 1

[DEBUG]
VERBOSE = 0