[DATA]
BASE_PATH_3D = data/singleVentricleData
; BASE_PATH_3D = data/singleVentricleData_cut
; BASE_PATH_3D = data/singleVentricleData_prolongationCubic
; BASE_PATH_3D = results/Synthetic3D_noise_0.01
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx
; PATIENT_NAME = Adolescent_17
; PATIENT_NAME = Adult_30
; PATIENT_NAME = SyntheticPatient_1

# Results from optical flow computation
FWD_OPTFLOW_RESULTS_DIR = results/data_of/TVL1OF3DForward_20220419-152113
BWD_OPTFLOW_RESULTS_DIR = results/data_of/TVL1OF3DBackward_20220419-152751

OUTPUT_PATH = results
TRAINED_MODEL = results/CNN_20220420-162246/model.pth


[DEVICE]
CUDA_AVAILABLE = 1
CUDA_DEVICE = 2


[PARAMETERS]
NUM_CLASSES = 1
INPUT_CHANNELS = 2
NUM_LAYERS = 4
FEATURES_START = 32
DROPOUT = 0
DROPOUT_PROB = 0.5
KERNEL_SIZE = 3,3,3
PADDING = 1
TRILINEAR = 0
NUM_EPOCHS = 500
BATCH_SIZE = 1
SHUFFLE = 1
LR = 0.001


[WARPING]
#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
; InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


[DEBUG]
VERBOSE = 1