[DATA]
BASE_PATH_3D = data/test_new_patient_prep

VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

# If not, choose single patient:
COMPUTE_ALL_PATIENTS = 0
PATIENT_NAME = patient070

OUTPUT_PATH = results/prep_OF


[DEVICE]
cuda_availabe = 1


[PARAMETERS]
# Forward -> propagation from m0 to mk
# Backward -> propagation from mk to m0
; Forward, Backward
mode = Forward
# cycle, ed_es
direction = cycle

use_indices = 0
; train, val, test, full
dataset = full
from_idx = 0
to_idx = 20

useAnisotropicDifferentialOp = 1
anisotropicDifferentialOp_alpha = 5.
anisotropicDifferentialOp_beta = 0.5

useGaussianBlur = 1
GaussianBlurSigma = 1.0

# Apply median filter to optical flow estimation
USE_MEDIAN_FILTER = 1
KERNEL_MF = 3

NUM_SCALES = 3
MAX_WARPS = 15
MAX_OUTER_ITERATIONS = 300

# Lambda is weight_Matching
weight_Matching = 1.0
weight_TV = 0.025

PRIMALDUAL_ALGO_TYPE = 2
sigma = 0.5
tau = 0.5
theta = 0.25
gamma = 1.0

#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
; InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


[DEBUG]
useDebugOutput = 0