[DATA]
BASE_PATH_3D = singleVentricleData
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx
PATIENT_NAME = Adult_30
#PATIENT_NAME = Adolescent_87
#PATIENT_NAME = Child_10
OUTPUT_PATH = results

[DEVICE]
cuda_availabe = 1


[PARAMETERS]
NUM_SCALES = 3
MAX_WARPS = 25
MAX_OUTER_ITERATIONS = 300


primalFctWeight_Matching = 1.
dualFctWeight_TV = 0.025

PRIMALDUAL_ALGO_TYPE = 2
sigma = 0.5
tau = 0.5
theta = 0.25
gamma = 1.

#InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = ZERO
; BoundaryType = NEAREST
; BoundaryType = MIRRO
BoundaryType = REFLECT

[DEBUG]
useDebugOutput = 1




