[DATA]
TRAINED_MODEL_DIR = results/FT_20220815-150206
MODEL_NAME = checkpoint.pth
OUTPUT_PATH = results

; train, val, test
DATASET = test
FINE_TUNING = 1


[PARAMETERS]
# Saving images size
save_NZ = 16
save_NY = 200
save_NX = 200

NUM_WORKERS = 8


[DEBUG]
SAVE_IMGS = 1
SAVE_NIFTI = 0