[DATA]
data_dir = data/svd_segmentation
output_dir = results_2023
                

[PARAMETERS]
; PRETRAINED = 0
; CHECKPOINT_FILE = results/some_checkpoint.pth

; Early stop. stop the training if the 'WHICH' acc has not
; been improved for the number of epochs specified
; PATIENCE = 50
; test, val
; WHICH = val

; unet3d, basic_unet3d, res_unet3d, unet, unetr
net = unetr
num_layers = 4
features_start = 16
img_size = 80
num_classes = 1
input_channels = 1
; sigmoid, softmax none
out_layer = none
; for unetr only
hidden_size = 768
mlp_dim = 3072
num_heads = 12
num_res_units = 0

num_epochs = 500
batch_size = 1
num_gpus = 1
num_workers = 8

; Optim Adam
lr = 1e-3
weight_decay = 1e-5
beta1 = 0.9
beta2 = 0.999

; LR Schedule
step_size = 50
gamma = 0.8


[DATA_AUGMENTATION]
; ======== Geometric transformations ========

; Flip
HORIZONTAL_FLIP_PROB = 0.5
VERTICAL_FLIP_PROB = 0.5
DEPTH_FLIP_PROB = 0.5

; Rotation
ROT_PROB = 1.0
ROT_X_RANGE = 0,0
ROT_Y_RANGE = 0,0
ROT_Z_RANGE = 0,360
; zeros, border, reflection
ROT_BOUNDARY = border

# Elastic deformation
ED_PROB = 0.05
ED_GRID = 10
ED_SIGMA_RANGE = 0.5,2.0
; mirror, reflect, constat, nearest
ED_BOUNDARY = nearest
ED_USE_PREFILTER = 0
; zyx, yx
ED_AXIS = yx
ED_ORDER = 1

; ======== Intesity transformations ========

; Multiplicative scaling
MULT_SCALING_PROB = 0.3
MULT_SCALING_RANGE = 0.9,1.1

; Additive scaling
ADD_SCALING_PROB = 0.1
ADD_SCALING_MEAN = 0.0
ADD_SCALING_STD = 0.05

; Gamma scaling
GAMMA_SCALING_PROB = 0.5
GAMMA_SCALING_RANGE = 0.8,1.2

; Gaussian noise
NOISE_PROB = 0.1
NOISE_MU = 0.0
NOISE_STD = 0.015

CLIP_INTERVAL = 0.0,1.0


[WARPING]
; LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; NEAREST, LINEAR, CUBIC_HERMITESPLINE
InterpolationType = LINEAR

; BoundaryType = NEAREST, REFLECT, MIRROR
BoundaryType = MIRROR


[DEBUG]
VERBOSE = 1
