[DATA]
TRAINED_MODEL_DIR = results_george/CNN_20221130-200627
MODEL_NAME = best_val_checkpoint.pth

BASE_PATH_3D = data/singleVentricleData_split
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx
PATIENT_NAME = Adult_11

OUTPUT_PATH = results/EVAL

; train, val, test, full
DATASET = test
FINE_TUNING = 0


[PARAMETERS]
PREDICT_CARDIAC_CYCLE = 0

# Saving images size
save_NZ = 16
save_NY = 96
save_NX = 96

NUM_WORKERS = 8


[DEBUG]
SAVE_IMGS = 0
SAVE_NIFTI = 0