[DATA]
PRETRAINED_DIR = data/singleVentricleData_split_avg/CNN_20220716-080546
WEIGHTS_FILENAME = weights.pth
PATIENT_NAME = Adolescent_1

OUTPUT_PATH = results


[PARAMETERS]
NUM_EPOCHS = 500
NUM_GPUS = 1
NUM_WORKERS = 1

# Optim Adam
LR = 1e-3
WEIGHT_DECAY = 1e-3
BETA1 = 0.9
BETA2 = 0.999

# Schedule
STEP_SIZE = 50
GAMMA = 0.8

LOSS_FN = mse
; LOSS_FN = huber
; HUBER_DELTA = 1.35
LOSS_REDUCTION = mean
LOSS_LAMBDA = 1000


[WARPING]
#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
InterpolationType = LINEAR
; InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT