[DATA]
OUTPUT_PATH = results

##2D##
BASE_PATH_2D = data/MiddleburyOpticalFlow
Image0_SUB_PATH = other-data-gray/Beanbags/frame07.png
Image1_SUB_PATH = other-data-gray/Beanbags/frame08.png

[DEVICE]
cuda_availabe = 1


[PARAMETERS]
#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtY = 1
; LenghtX = 1

useGaussianBlur = 1
GaussianBlurSigma = 2.

NUM_SCALES = 3
MAX_WARPS = 25
MAX_OUTER_ITERATIONS = 1000

primalFctWeight_Matching = 1.
dualFctWeight_TV = 0.5

PRIMALDUAL_ALGO_TYPE = 2
sigma = 0.5
tau = 0.5
theta = 0.25
gamma = 1.

; InterpolationType = LINEAR
InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT

[DEBUG]
useDebugOutput = 1




