[DATA]
BASE_PATH_3D = data/singleVentricleData_cut_r
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

OUTPUT_PATH = results

VALIDATION_PATIENTS = {'Adolescent_1',
                        'Adolescent_20',
                        'Adolescent_53',
                        'Adolescent_62',
                        'Adult_3',
                        'Adult_11',
                        'Adult_24',
                        'Adult_36',
                        'Child_2',
                        'Child_14',
                        'Child_24',
                        'Child_36'}


[PARAMETERS]
FLIP_MASKS = 0

# Create new N patientes for each patient in the original dataset
CREATE_NEW = 20

# Flip probabilities
FLIP_X_PROB = 0.5
FLIP_Y_PROB = 0.5
FLIP_Z_PROB = 0.5

# Rotation probability and ranges
ROT_PROB = 1.0
ROT_X_RANGE = 0,0
ROT_Y_RANGE = 0,0
ROT_Z_RANGE = -180,180

# Elastic deformation probability and params
ELASTIC_DEFORM_PROB = 0.5
ELASTIC_DEFORM_GRID = 10
ELASTIC_DEFORM_SIGMA = 2

SAVE_ORIGINAL_DATA = 1
SAVE_VAL_DATA = 1