[DATA]
; BASE_PATH_3D = data/singleVentricleData
BASE_PATH_3D = data/singleVentricleData_cut
;BASE_PATH_3D = results/DA_20220614-154459
; BASE_PATH_3D = data/singleVentricleData_prolongationCubic
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx
; PATIENT_NAME = Adolescent_17
; PATIENT_NAME = SyntheticPatient_1

# Results from optical flow computation
FWD_OPTFLOW_RESULTS_DIR = results/singleVentricleData_cut_r_OF/TVL1OF3DForward_20220615-214723
BWD_OPTFLOW_RESULTS_DIR = results/singleVentricleData_cut_r_OF/TVL1OF3DBackward_20220615-214808

OUTPUT_PATH = results

VALIDATION_PATIENTS = {'Adolescent_1',
                        'Adolescent_20',
                        'Adolescent_53',
                        'Adolescent_62',
                        'Adult_3',
                        'Adult_11',
                        'Adult_24',
                        'Adult_36',
                        'Child_2',
                        'Child_14',
                        'Child_24',
                        'Child_36'}

[DEVICE]
CUDA_AVAILABLE = 1
CUDA_DEVICE = 5


[PARAMETERS]
USE_MEDIAN_FILTERED_FLOW = 1
FLIP_MASKS = 0

NUM_CLASSES = 1
INPUT_CHANNELS = 2
DROPOUT = 0
DROPOUT_PROB = 0.5
KERNEL_SIZE = 3,3,3
PADDING = 1
TRILINEAR = 0
NUM_EPOCHS = 500
BATCH_SIZE = 1
SHUFFLE = 1

# possible tuning of parameters:
# options: 3 or 4?
NUM_LAYERS = 4
# options: 8,16
FEATURES_START = 16

# Optim Adam
LR = 0.001
WEIGHT_DECAY = 0
BETA1 = 0.9
BETA2 = 0.999

# Schedule
STEP_SIZE = 50
GAMMA = 1.0


[WARPING]
#LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
InterpolationType = LINEAR
; InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


[DEBUG]
VERBOSE = 1