[DATA]
TRAINED_MODEL_DIR = results/FT_20220726-120214
MODEL_NAME = model.pth
OUTPUT_PATH = results

; options: train, val
DATASET = val
FINE_TUNING = 1


[PARAMETERS]
# Saving images size
save_NZ = 16
save_NY = 200
save_NX = 200

NUM_WORKERS = 1


[DEBUG]
SAVE_IMGS = 1
SAVE_NIFTI = 1