[DATA]
BASE_PATH_3D = data/0preprocessing/singleVentricleData_flip
VOLUMES_SUBDIR_PATH = NIFTI_4D_Datasets
SEGMENTATIONS_SUBDIR_PATH = NIFTI_Single_Ventricle_Segmentations
SEGMENTATIONS_FILE_NAME = Segmentation_volumes.xlsx

OUTPUT_PATH = results

[DEVICE]
cuda_availabe = 1
cuda_device = 1


# 1
[FLIPPING]
flip_all = {Adolescent_7,
            Adolescent_26,
            Adolescent_54,
            Adolescent_75,
            Adult_6,
            Adult_11,
            Adult_16,
            Adult_17,
            Child_27}


# 2
[NORMALIZATION]


# 3
[CUTTING]
xTol = 10
yTol = 10
zTol = 10


# 4
[PROLONGATION]
NX_prolong = 80
NY_prolong = 80
NZ_prolong = 80
; NZ_prolong = 16

# Threshold for prolongated mask binarization
USE_TH = 1
BIN_TH = 0.5

# Pad time
PAD_TIME = 40

; LenghtType: numDofs or fixed
LenghtType = numDofs
; LenghtType = fixed
; LenghtZ = 1
; LenghtY = 1
; LenghtX = 1

; InterpolationType = NEAREST
InterpolationType = LINEAR
; InterpolationType = CUBIC_HERMITESPLINE

; BoundaryType = NEAREST
BoundaryType = MIRROR
; BoundaryType = REFLECT


# 5
[SPLIT]
validation_patients = {Adolescent_1,
                        Adolescent_62,
                        Adolescent_107,
                        Adult_3,
                        Adult_24,
                        Adult_36,
                        Adult_62,
                        Adult_104,
                        Child_14,
                        Child_24,
                        Child_36,
                        Child_45,
                        Child_53,
                        patient001,
                        patient005,
                        patient010,
                        patient015,
                        patient020,
                        patient025,
                        patient030,
                        patient035,
                        patient040,
                        patient045,
                        patient050,
                        patient055,
                        patient060,
                        patient065,
                        patient070,
                        patient075,
                        patient080,
                        patient085,
                        patient090,
                        patient095}

test_patients = {Adolescent_53,
                Adult_11,
                Child_73}


# 6
[DATA_AUGMENTATION]
# Create new N patientes for each patient in the original dataset
CREATE_NEW = 1

# Flip probabilities
FLIP_X_PROB = 0.0
FLIP_Y_PROB = 0.0
FLIP_Z_PROB = 0.0

# Rotation probability and ranges
ROT_PROB = 0.0
ROT_X_RANGE = 0,0
ROT_Y_RANGE = 0,0
ROT_Z_RANGE = 20,340
ROT_DEFORM_BDRYMODE = nearest

# Elastic deformation probability and params
ELASTIC_DEFORM_PROB = 1.0
ELASTIC_DEFORM_GRID = 10
ELASTIC_DEFORM_SIGMA_MIN = 0.5
ELASTIC_DEFORM_SIGMA_MAX = 2.5
ELASTIC_DEFORM_BDRYMODE = constant
; ELASTIC_DEFORM_BDRYMODE = mirror
; ELASTIC_DEFORM_BDRYMODE = reflect
ELASTIC_DEFORM_USE_PREFILTER = 0
