[DATA]
root_dir = data/singleVentricleData
output_dir = results/preprocessed
dst_images_folder = images
dst_labels_folder = labels


[TRANSFORMS]
to_ras = 1
crop_fg = 1
norm = 1
norm_q2 = 95
; if any -1 leave image unchanged
size = (80,80,80)


[VIZ]
viz_dir = viz
save_png = 0
; if any -1 leave image unchanged
size = (16,80,80)
; create gif only if png images where created first
save_gif = 0
dur_gif = 150