[DATA]
BASE_PATH_3D = data/svd_segmentation
OUTPUT_PATH = results
                

[PARAMETERS]
NUM_EPOCHS = 500
; Early stop
PATIENCE = 50

; unet3d, basic_unet3d, res_unet3d, unet, unetr
NET = unetr
IMG_SIZE = 96
NUM_CLASSES = 1
INPUT_CHANNELS = 1
; 3,4,5
NUM_LAYERS = 4
; 8,16,32
FEATURES_START = 16
; for unetr only
HIDDEN_SIZE = 768
MLP_DIM = 3072
NUM_HEADS = 12

NUM_RES_UNITS = 0

;relu, prelu, leaky_relu
ACTIVATION = leaky_relu
ACTIVATION_SLOPE = 0.1

KERNEL_SIZE = 3,3,3
PADDING = 1
TRILINEAR = 0
RESIDUAL = 0
; sigmoid, none
OUT_LAYER = none

; Options: 1,4,8
BATCH_SIZE = 4

; CPU for data loading
NUM_WORKERS = 4

; Optim Adam
LR = 1e-3
WEIGHT_DECAY = 0
BETA1 = 0.9
BETA2 = 0.999

; LR Schedule
STEP_SIZE = 500
GAMMA = 0.8


[DATA_AUGMENTATION]
; ======== Geometric transformations ========

; Flip
HORIZONTAL_FLIP_PROB = 0.0
VERTICAL_FLIP_PROB = 0.0
DEPTH_FLIP_PROB = 0.0

; Rotation
ROT_PROB = 0.0
ROT_X_RANGE = 0,0
ROT_Y_RANGE = 0,0
ROT_Z_RANGE = 0,360
; zeros, border, reflection
ROT_BOUNDARY = border

# Elastic deformation
ED_PROB = 0.0
ED_GRID = 10
ED_SIGMA_RANGE = 0.5,2.0
; mirror, reflect, constat, nearest
ED_BOUNDARY = nearest
ED_USE_PREFILTER = 0
; zyx, yx
ED_AXIS = yx
ED_ORDER = 1

; ======== Intesity transformations ========

; Multiplicative scaling
MULT_SCALING_PROB = 0.0
MULT_SCALING_RANGE = 0.9,1.1

; Additive scaling
ADD_SCALING_PROB = 0.0
ADD_SCALING_MEAN = 0.0
ADD_SCALING_STD = 0.05

; Gamma scaling
GAMMA_SCALING_PROB = 0.0
GAMMA_SCALING_RANGE = 0.8,1.2

; Gaussian noise
NOISE_PROB = 0.0
NOISE_MU = 0.0
NOISE_STD = 0.015