[DATA]
dataset = singleVentricleData
num_classes = 2
root_dir = results/preprocessed/%(dataset)s
output_dir = results/voxelmorph/%(dataset)s

MODEL = results/voxelmorph/singleVentricleData/fold_0_20230420-050705/checkpoint_final.pth
PATIENT = Child_73

[PARAMETERS]
NUM_EPOCHS = 20
IMG_SIZE = 96
WORKERS = 2
BIDIR = 0
; mse | ncc
IMG_LOSS = mse
LAMBDA = 0.01
LR = 1e-4
CUDNN_NONDET = 1
