[DATA]
ROOT_DIR = data/svd_segmentation
OUTPUT_DIR = results


[PARAMETERS]
NUM_EPOCHS = 500
BATCH_SIZE = 1
IMG_SIZE = 96
WORKERS = 8
ENC_FEAT = 16,32,32,32
DEC_FEAT = 32,32,32,32,32,16,16
INT_STEPS = 7
INT_DOWNSIZE = 2
BIDIR = 0
; mse | ncc
IMG_LOSS = mse
LAMBDA = 0.01
LR = 1e-4
CUDNN_NONDET = 1


[DATA_AUGMENTATION]