[DATA]
ROOT_DIR = results/preprocessed/singleVentricleData/
OUTPUT_DIR = results/vxm


[PARAMETERS]
NUM_EPOCHS = 500
BATCH_SIZE = 1
IMG_SIZE = 96
WORKERS = 8
ENC_FEAT = 16,32,32,32
DEC_FEAT = 32,32,32,32,32,16,16
INT_STEPS = 7
INT_DOWNSIZE = 2
BIDIR = 0
; mse | ncc
IMG_LOSS = ncc
LAMBDA = 0.01
LR = 1e-4
CUDNN_NONDET = 1


[DATA_AUGMENTATION]
; ======== Geometric transformations ========

; Flip
HORIZONTAL_FLIP_PROB = 0.0
VERTICAL_FLIP_PROB = 0.0
DEPTH_FLIP_PROB = 0.0

; Rotation
ROT_PROB = 0.0
ROT_X_RANGE = 0,0
ROT_Y_RANGE = 0,0
ROT_Z_RANGE = 0,360
; zeros, border, reflection
ROT_BOUNDARY = border

# Elastic deformation
ED_PROB = 0.0
ED_GRID = 10
ED_SIGMA_RANGE = 0.5,2.0
; mirror, reflect, constat, nearest
ED_BOUNDARY = nearest
ED_USE_PREFILTER = 0
; zyx, yx
ED_AXIS = yx
ED_ORDER = 1

; ======== Intesity transformations ========

; Gamma scaling
GAMMA_SCALING_PROB = 0.0
GAMMA_SCALING_RANGE = 0.8,1.2
