[DATA]
ROOT_DIR = data/svd_segmentation
OUTPUT_DIR = results

MODEL = results/VXM_20230404-205114/model.pth
PATIENT = Child_73


[PARAMETERS]
NUM_EPOCHS = 20
IMG_SIZE = 96
WORKERS = 2
BIDIR = 0
; mse | ncc
IMG_LOSS = mse
LAMBDA = 0.01
LR = 1e-4
CUDNN_NONDET = 1